[dpool/home]
	use_template = production
	recursive = true
	process_children_only = true

[template_production]
        frequently = 0
        hourly = 36
        daily = 30
        monthly = 3
        yearly = 0
        autosnap = yes
        autoprune = yes
