---
- hosts: all
  connection: local

  pre_tasks:
    - name: Install and enable requirements
      block:
        - name: Install required python packages
          package:
            name: ['python-pip', 'python3-pip', 'python3-setuptools']
        - name: Install snaps
          snap:
            name: "{{ item.name }}"
            state: present
            classic: "{{ item.classic | default(false) }}"
          with_items:
            - "{{ snaps_group | default([]) }}"
            - "{{ snaps | default([]) }}"
          become: true
          tags:
            - packages
      become: true

  roles:
    - {role: azmodude.packages, tags: ['packages']}
    - {role: azmodude.google-chrome, tags: ['packages']}
    - {role: azmodude.users, tags: ['users', 'system']}
    - {role: azmodude.pyenv, tags: ['python', 'packages']}
    - {role: azmodude.unclutter-xfixes, tags: ['packages', 'i3']}
    - {role: samba, when: install_samba, tags: ['system', 'samba', 'services']}
    - {role: misc, tags: ['system']}

  tasks:
    - name: Install Python user packages
      pip:
        executable: "{{ item.pip | default('pip') }}"
        name: "{{ item.name }}"
        extra_args: --user
        version: "{{ item.version | default(omit) }}"
      with_items: "{{ pip_user_packages }}"
      when: pip_user_packages is defined
      tags:
        - python
        - pip

    - name: Install Ruby user gems
      gem:
        name: "{{ item.name }}"
        user_install: true
      with_items: "{{ ruby_user_gems }}"
      tags:
        - ruby
      when: ruby_user_gems is defined

    - name: Install go applications
      shell: "go get {{ item.url }}"
      environment:
        GOPATH: "{{ GOPATH }}"
      with_items: "{{ go_get }}"
      when: go_get is defined
      changed_when: false
      become: azmo
      tags:
        - go
