---
- hosts: all
  connection: local

  pre_tasks:
    - name: Install and enable requirements
      block:
        - name: Install required python packages
          package:
            name: ["python3-pip", "python3-setuptools"]
      become: true

  tasks:
    - name: Install packages
      import_role:
        name: azmodude.packages
      tags:
        - packages
    - name: Create users
      import_role:
        name: azmodude.users
      tags:
        - system
        #    - name: Install Google-Chrome
        #      import_role:
        #        name: azmodude.google-chrome
        #      tags:
        #        - packages
    - name: Install pyenv
      import_role:
        name: azmodude.pyenv
      tags:
        - packages
        - python
    - name: Install samba and template configuration
      import_role:
        name: samba
      when: install_samba
      tags:
        - system
        - services
        - samba
    - name: Install fonts
      import_role:
        name: fonts
      tags:
        - fonts
    - name: Configure Gnome settings
      import_role:
        name: gnome
      tags:
        - gnome
      when: gnome_installed

    - name: Do miscellaneous configuration tasks
      import_role:
        name: miscellaneous
      tags:
        - system
        - misc

    - name: Do host specific configuration tasks
      include_role:
        name: hosts
      tags:
        - system
        - host

    - name: Install Python user packages
      pip:
        executable: "{{ item.pip | default('pip') }}"
        name: "{{ item.name }}"
        extra_args: --user
        version: "{{ item.version | default(omit) }}"
      with_items: "{{ pip_user_packages }}"
      when: pip_user_packages is defined
      tags:
        - python
        - pip
    - name: Install Ruby user gems
      gem:
        name: "{{ item.name }}"
        user_install: true
      with_items: "{{ ruby_user_gems }}"
      tags:
        - ruby
      when: ruby_user_gems is defined
    - name: Install go applications
      command: "go get {{ item.url }}"
      environment:
        GOPATH: "{{ GOPATH }}"
      with_items: "{{ go_get }}"
      when: go_get is defined
      changed_when: false
      become: azmo
      tags:
        - go
