---
- src: https://github.com/azmodude/ansible-role-pyenv
  name: azmodude.pyenv
- src: https://github.com/azmodude/ansible-role-packages
  name: azmodude.packages
- src: https://github.com/azmodude/ansible-role-users
  name: azmodude.users
- src: https://github.com/jaredhocutt/ansible-gnome-extensions.git
