---
- name: Check for SSH and GPG Gnome Keyring desktop files
  stat:
    path: /etc/xdg/autostart/gnome-keyring-{{ item }}.desktop
  with_items:
    - ssh
    - pkcs11
  register: keyring

- name: Copy desktop files to .disabled
  copy:
    src: "{{ item.stat.path }}"
    dest: "{{ item.stat.path}}.disabled"
  with_items: "{{ keyring.results }}"
  when: item.stat.exists
  become: true

- name: Nuke Gnome Keyring SSH and GPG desktop files
  file:
    path: "{{ item.stat.path }}"
    state: absent
  with_items: "{{ keyring.results }}"
  when: item.stat.exists
  become: true

