---
- import_tasks: pacman.yml
- import_tasks: logind.yml
  when: not gnome_installed

- name: Get btrbk in shape
  block:
    - name: Ensure /etc/btrbk exists
      file:
        path: /etc/btrbk
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Template btrbk.conf
      template:
        src: etc/btrbk/btrbk.conf
        dest: /etc/btrbk/btrbk.conf
        backup: true
        owner: root
        group: root
        mode: 0644
    - name: Template btrbk-to-external-drive.conf
      template:
        src: etc/btrbk/btrbk-to-external-drive.conf
        dest: /etc/btrbk/btrbk-to-external-drive.conf
        backup: true
        owner: root
        group: root
        mode: 0644
    - name: Ensure /etc/systemd/system/btrbk.timer.d exists
      file:
        path: /etc/systemd/system/btrbk.timer.d
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Copy override.conf for btrbk.timer
      copy:
        src: etc/systemd/system/btrbk.timer.d/override.conf
        dest: /etc/systemd/system/btrbk.timer.d/override.conf
        owner: root
        group: root
        mode: 0644
      notify: Reload systemd
  become: true

- name: Disable pcspeaker
  copy:
    src: etc/modprobe.d/nobeep.conf
    dest: /etc/modprobe.d/nobeep.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy NetworkManager Dispatcher Scripts
  copy:
    src: "{{ item }}"
    dest: "/etc/NetworkManager/dispatcher.d/"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - "etc/NetworkManager/dispatcher.d/*"
  become: true

- name: Enable and start services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - avahi-daemon.service
    - btrbk.timer
    - docker.service
    - org.cups.cupsd
    - bluetooth.service
    - pcscd.socket
    - libvirtd.socket
    - fstrim.timer
    - NetworkManager.service
  become: true

- name: Enable and start services (conditional)
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - acpid
  become: true
  when: gnome_installed is not true

- name: Enable and start user services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    scope: user
  with_items:
    - ssh-agent.service
    - gpg-agent.service
    - borgmatic-prune-create.timer
    - borgmatic-check.timer
    - borgmatic-rclone.timer
    - systemd-tmpfiles-setup.service
    - systemd-tmpfiles-clean.timer

- name: Extend maximum number of inotify watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
  become: true

- name: Set pinentry-qt when using KDE
  set_fact:
    pinentry: /usr/bin/pinentry-qt
  when: '"XDG_SESSION_DESKTOP" in ansible_env and ansible_env["XDG_SESSION_DESKTOP"] == "KDE"'
- name: Set pinentry-gtk-2 when using anything GTK based
  set_fact:
    pinentry: /usr/bin/pinentry-gtk-2
  when: '"XDG_SESSION_DESKTOP" not in ansible_env or ("XDG_SESSION_DESKTOP" in ansible_env and ansible_env["XDG_SESSION_DESKTOP"] in ("GNOME", "ubuntu", "gnome-xorg", "i3", "gnome"))'
- name: Check for current pinentry
  stat:
    path: /usr/bin/pinentry
  register: pinentry_current

- name: Set pinentry to desired state
  block:
    - name: Nuke old pinentry link
      file:
        path: /usr/bin/pinentry
        state: absent
    - name: Set new pinentry link
      file:
        path: /usr/bin/pinentry
        src: "{{ pinentry }}"
        state: link
  become: true
  when: pinentry_current.stat.islnk and pinentry_current.stat.lnk_target != pinentry
