---
- name: Enable and start services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - libvirtd
    - fstrim.timer
    - docker
  become: true

- name: Enable services for notebooks
  block:
    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - tlp

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: true
      with_items:
        - []
  when: ansible_form_factor == 'Notebook'
  become: true

- name: Enable and start user services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    scope: user
  with_items:
    - ssh-agent.service
    - gpg-agent.service

- name: Extend maximum number of inotify watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
  become: true
