---
- import_tasks: pacman.yml

- name: Enable and start services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - libvirtd
    - docker
    - org.cups.cupsd
    - bluetooth
    - pcscd
    - fstrim.timer
    - sanoid.timer
  become: true

- name: Enable and start user services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    scope: user
  with_items:
    - ssh-agent.service
    - gpg-agent.service

- name: Get sanoid in shape
  block:
    - name: Check whether sanoid.conf.sample already exists
      stat:
        path: /etc/sanoid/sanoid.conf.sample
      register: sanoid_conf

    - name: Move sanoid.conf to sanoid.conf.sample
      copy:
        src: /etc/sanoid/sanoid.conf
        dest: /etc/sanoid/sanoid.conf.sample
      when: not sanoid_conf.stat.exists

    - name: Template sanoid.conf
      template:
        src: sanoid.conf
        dest: /etc/sanoid/sanoid.conf
        backup: true
        owner: root
        group: root
        mode: 0644
  become: true

- name: Extend maximum number of inotify watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
  become: true

- set_fact:
    pinentry: /usr/bin/pinentry-qt
  when: '"XDG_SESSION_DESKTOP" in ansible_env and ansible_env["XDG_SESSION_DESKTOP"] == "KDE"'
- set_fact:
    pinentry: /usr/bin/pinentry-gtk-2
  when: '"XDG_SESSION_DESKTOP" not in ansible_env or ("XDG_SESSION_DESKTOP" in ansible_env and ansible_env["XDG_SESSION_DESKTOP"] in ("GNOME", "ubuntu", "gnome-xorg", "i3", "gnome"))'
- name: Check for current pinentry
  stat:
    path: /usr/bin/pinentry
  register: pinentry_current

- name: Set pinentry to desired state
  block:
    - name: Nuke old pinentry link
      file:
        path: /usr/bin/pinentry
        state: absent
    - name: Set new pinentry link
      file:
        path: /usr/bin/pinentry
        src: "{{ pinentry }}"
        state: link
  become: true
  when: pinentry_current.stat.islnk and pinentry_current.stat.lnk_target != pinentry
