---
- name: Enable pacman options
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#{{ item }}'
    line: '{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - "Color"
    - "TotalDownload"
    - "VerbosePkgLists"
  become: true
