---
resticprofile_bin: /usr/local/bin
resticprofile_status_directory: /var/log/resticprofile
resticprofile_config_directory: /etc/resticprofile
resticprofile_config: profiles.yaml
resticprofile_schedule:
  - workstations-borgbase
  # - workstations-backblaze
  - workstations-zeus

  # run-after: "curl -s --output /dev/null --form-string 'token={{ .backup.pushover.token }}' --form-string 'user={{ .backup.pushover.userKey }}' --form-string \"message=Restic $PROFILE_COMMAND successful on host '{{ .chezmoi.hostname }}' for profile '$PROFILE_NAME'.\" https://api.pushover.net/1/messages.json"
  # run-after-fail:
  #   - "curl -s --output /dev/null --form-string 'token={{ .backup.pushover.token }}' --form-string 'user={{ .backup.pushover.userKey }}'  --form-string \"message=Restic $PROFILE_COMMAND failed on host '{{ .chezmoi.hostname }}' for profile '$PROFILE_NAME' with error: $ERROR.\" https://api.pushover.net/1/messages.json"
  #   {{ if eq .chezmoi.hostname "apollo" }}
  #   - curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/8dd8e851-e4a6-4e4c-832d-705ef1885499/fail
  #   {{ end }}
# workstations-backblaze:
#   inherit: "default"
#   repository: "{{ .backup.restic.backblaze.repositoryUrl }}"
#   limit-upload: 3000
#
#   env:
#     B2_ACCOUNT_ID: "{{ .backup.restic.backblaze.accountId }}"
#     B2_ACCOUNT_KEY: "{{ .backup.restic.backblaze.accountKey }}"
#
#   backup:
#     source: /home/azmo
#
#     schedule: "00/2:30"
#     schedule-permission: "system"
#
#   retention:
#     before-backup: false
#     after-backup: true
#     keep-last: 30
#     keep-hourly: 24
#     keep-daily: 30
#     keep-weekly: 4
#     keep-monthly: 12
#     keep-yearly: 0
#     keep-within: "6h"
#     tag: true
#
#   forget:
#     keep-last: 30
#     keep-hourly: 24
#     keep-daily: 30
#     keep-weekly: 4
#     keep-monthly: 12
#     keep-yearly: 0
#     keep-within: "6h"
#     tag: true
#
#   check:
#     cache-dir: "{{ .Env.XDG_CACHE_HOME }}/restic-check"
#     with-cache: true
#     read-data: false
#     schedule: "Sun,Wed 10:30"
#     schedule-permission: "system"
#
#   prune:
#     schedule: "Sun 14:30"
#     schedule-permission: "system"
#
# workstations-scaleway:
#   inherit: "default"
#   repository: "{{ .backup.restic.scaleway.repositoryUrl }}"
#   limit-upload: 3000
#   option:
#     - "s3.region=fr-par"
#
#   env:
#     AWS_ACCESS_KEY_ID: "{{ .backup.restic.scaleway.accessKeyId }}"
#     AWS_SECRET_ACCESS_KEY: "{{ .backup.restic.scaleway.accessKeySecret }}"
#
#   backup:
#     source: /home/azmo
#
#     schedule: "00/2:30"
#     schedule-permission: "system"
#
#   retention:
#     before-backup: false
#     after-backup: true
#     keep-last: 3
#     keep-hourly: 24
#     keep-daily: 14
#     keep-weekly: 4
#     keep-monthly: 12
#     keep-yearly: 0
#     keep-within: "6h"
#     tag: true
#
#   forget:
#     keep-last: 3
#     keep-hourly: 24
#     keep-daily: 14
#     keep-weekly: 4
#     keep-monthly: 12
#     keep-yearly: 0
#     keep-within: "6h"
#     tag: true
#
#   check:
#     cache-dir: "{{ .Env.XDG_CACHE_HOME }}/restic-check"
#     with-cache: true
#     read-data: false
#     schedule: "Sun,Wed 10:30"
#     schedule-permission: "system"
#
#   prune:
#     schedule: "Sun 14:30"
#     schedule-permission: "system"
#
