---
- name: Put xorg configuration files into place
  copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d"
    owner: root
    group: root
    mode: 0644
  with_fileglob: "{{ inventory_hostname }}/etc/X11/xorg.conf.d/*.conf"
  become: true
