---
- name: Ensure destination in {{ ansible_user_dir }}/.local/share/fonts is present
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts/{{ item }}"
    state: directory
  loop:
    - hack-nerd-font
- name: Install Fonts
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/{{ item.name }}/{{ item.dest }}"
  loop:
    - {name: "hack-nerd-font", url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf", dest: "Hack Bold Nerd Font Complete.ttf"}
    - {name: "hack-nerd-font", url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf", dest: "Hack Bold Italic Nerd Font Complete.ttf"}
    - {name: "hack-nerd-font", url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf", dest: "Hack Italic Nerd Font Complete.ttf"}
    - {name: "hack-nerd-font", url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf", dest: "Hack Regular Nerd Font Complete.ttf"}
  notify:
    - Regenerate font cache
